
language: python
python:
# current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install 
# command to run tests
script:
  - pipenv run pylint main.py

